### ISSUE TITLE
Filter feature

### ISSUE THREAD

**Issue by geeksesi** [geeksesi/shop-management#13]
# Story
as developer we should be able to list some filters that we will support for indexes API. like :
- example.com/products?category=1,2,3
- example.com/products?title=blahblah
- example.com/products?price=12&price_action=less_than

we should to have abstraction to manage this kind of filters where we want.

# Technicals
watch resources and write here what you want to do.

# DOD 
- [x] write abstraction full unit test
- [x] unit test on product model
- [x] use on product index controller with category and price filter 
- [x] write technical document about how to use and implement, ( make an wiki page and write it there )

# Resources : 
- https://spatie.be/docs/laravel-query-builder/v5/features/filtering
- https://appdividend.com/2022/03/01/how-to-create-filters-in-laravel/
- https://github.com/alirezabahram7/bfilter

**Comment by mj999666** [comment]
The end of this issue almost until Saturday

**Comment by mj999666** [comment]
At first I create a `Filters` folder inside the app directory
In that folder, create two file called `CategoryFilter.php` and `PriceFilter.php`.
This `CategoryFilterclass` is responsible for filtering the data based on the Category.
We pass the Category in the query string, and we get the result according to that.
This `PriceFilteris` responsible for filtering the data based on the Price.
We pass the Price in the query string, and we get the result according to that.
Inside the Filters folder, create one abstract class called `AbstractFilter.php`.
The only reason I have taken the above class as an abstract class is that, in the future, we have more than one kind of filter, so It is better to use this class as an abstract, and then a different filter class can extend this class so that we do not repeat each code every time.
The next step is to create a new file called `ProductFilter.php` inside the Filters directory. In this file, we will define the actual filter class ( Price and Category )
make `scopeFilter`  inside `Product` model and pass the full request as a parameter.
in `AbstractFilter`  we find all available filter from query string and then resolve that.
finally in every filter files ( category and price ) I will develop filter method
